version: '3'

services:
  app:
    image: votacao-pauta:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"  
  h2db:
    image: oscarfonts/h2:latest
    ports:
      - "8082:8082"
    environment:
      - H2_CONSOLE_PORT=8082
      - H2_OPTIONS=-ifNotExists -webAllowOthers
    volumes:
      - /caminho/no/host:/h2-data
